# -*- coding: utf-8 -*-
"""
Created on Sat Nov 21 15:24:22 2015

Hardcoded conference non-divisional opponents that you play 4 times

@author: charlesliu
"""

conf_opponents = {'76ers': {'Bucks', 'Hawks', 'Heat', 'Pacers', 'Pistons', 'Wizards'},
 'Bucks': {'76ers', 'Hawks', 'Heat', 'Knicks', 'Magic', 'Nets'},
 'Bulls': {'Celtics', 'Hornets', 'Magic', 'Nets', 'Raptors', 'Wizards'},
 'Cavaliers': {'Celtics', 'Hawks', 'Heat', 'Nets', 'Raptors', 'Wizards'},
 'Celtics': {'Bulls', 'Cavaliers', 'Heat', 'Hornets', 'Magic', 'Pacers'},
 'Clippers': {'Grizzlies',
  'Jazz',
  'Nuggets',
  'Rockets',
  'Spurs',
  'Trailblazers'},
 'Grizzlies': {'Clippers',
  'Jazz',
  'Kings',
  'Lakers',
  'Thunder',
  'Trailblazers'},
 'Hawks': {'76ers', 'Bucks', 'Cavaliers', 'Nets', 'Pistons', 'Raptors'},
 'Heat': {'76ers', 'Bucks', 'Cavaliers', 'Celtics', 'Nets', 'Pacers'},
 'Hornets': {'Bulls', 'Celtics', 'Knicks', 'Pacers', 'Pistons', 'Raptors'},
 'Jazz': {'Clippers',
  'Grizzlies',
  'Kings',
  'Mavericks',
  'Rockets',
  'Warriors'},
 'Kings': {'Grizzlies', 'Jazz', 'Nuggets', 'Pelicans', 'Spurs', 'Thunder'},
 'Knicks': {'Bucks', 'Hornets', 'Magic', 'Pacers', 'Pistons', 'Wizards'},
 'Lakers': {'Grizzlies',
  'Mavericks',
  'Nuggets',
  'Pelicans',
  'Timberwolves',
  'Trailblazers'},
 'Magic': {'Bucks', 'Bulls', 'Celtics', 'Knicks', 'Pistons', 'Raptors'},
 'Mavericks': {'Jazz',
  'Lakers',
  'Suns',
  'Thunder',
  'Trailblazers',
  'Warriors'},
 'Nets': {'Bucks', 'Bulls', 'Cavaliers', 'Hawks', 'Heat', 'Wizards'},
 'Nuggets': {'Clippers', 'Kings', 'Lakers', 'Pelicans', 'Rockets', 'Spurs'},
 'Pacers': {'76ers', 'Celtics', 'Heat', 'Hornets', 'Knicks', 'Wizards'},
 'Pelicans': {'Kings',
  'Lakers',
  'Nuggets',
  'Thunder',
  'Timberwolves',
  'Warriors'},
 'Pistons': {'76ers', 'Hawks', 'Hornets', 'Knicks', 'Magic', 'Raptors'},
 'Raptors': {'Bulls', 'Cavaliers', 'Hawks', 'Hornets', 'Magic', 'Pistons'},
 'Rockets': {'Clippers',
  'Jazz',
  'Nuggets',
  'Suns',
  'Timberwolves',
  'Warriors'},
 'Spurs': {'Clippers',
  'Kings',
  'Nuggets',
  'Suns',
  'Timberwolves',
  'Trailblazers'},
 'Suns': {'Mavericks',
  'Rockets',
  'Spurs',
  'Thunder',
  'Timberwolves',
  'Trailblazers'},
 'Thunder': {'Grizzlies',
  'Kings',
  'Mavericks',
  'Pelicans',
  'Suns',
  'Warriors'},
 'Timberwolves': {'Lakers',
  'Pelicans',
  'Rockets',
  'Spurs',
  'Suns',
  'Warriors'},
 'Trailblazers': {'Clippers',
  'Grizzlies',
  'Lakers',
  'Mavericks',
  'Spurs',
  'Suns'},
 'Warriors': {'Jazz',
  'Mavericks',
  'Pelicans',
  'Rockets',
  'Thunder',
  'Timberwolves'},
 'Wizards': {'76ers', 'Bulls', 'Cavaliers', 'Knicks', 'Nets', 'Pacers'}}
